name: Node CI Legacy

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: voxpelli/ghatemplates/.github/workflows/test.yml@main
    with:
      node-versions: '12'
      npm-test-script: 'test-build-less'
